INSERT INTO ALIEN VALUES (101,'Kinjal', 'Javascript');
INSERT INTO ALIEN VALUES (102,'Navin', 'Java');
INSERT INTO ALIEN VALUES (103,'Kiran', 'Android');
INSERT INTO ALIEN VALUES (104,'Pravin', 'Python');
INSERT INTO ALIEN VALUES (105,'Komal', 'Java');